print('first line of code')
print('second line of code')
print('                                                third line of code')
print(123)

print('')
print('  X')
print(' XXX')
print('XXXXX')
print('  X')
print('  X')
print('  X')